version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin $DOCKER_REGISTRY

      - run:
          name: Pull cache image
          command: |
            docker pull $DOCKER_IMAGE:$CIRCLE_BRANCH || echo 'Image not exists.'

      - run:
          name: Build Docker
          command: |
            docker build --cache-from=$DOCKER_IMAGE:$CIRCLE_BRANCH -t $DOCKER_IMAGE:$CIRCLE_BRANCH .
            docker tag $DOCKER_IMAGE:$CIRCLE_BRANCH $DOCKER_IMAGE:$CIRCLE_SHA1

      - run:
          name: Push to Docker Hub
          command: |
            docker push $DOCKER_IMAGE:$CIRCLE_BRANCH
            docker push $DOCKER_IMAGE:$CIRCLE_SHA1

  deploy:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "4b:7a:f5:16:54:4a:18:5a:85:e8:1d:41:48:82:79:58"

      - run:
          name: Copy docker-compose to server
          command: |
            scp -P $PORT -r deploy/. $USER@$HOST:$PROJECT_ROOT
            ssh -p $PORT $USER@$HOST \
                "cd $PROJECT_ROOT && \
                docker-compose pull && \
                docker-compose up -d && \
                docker images -f 'dangling=true' -q | xargs -r docker rmi"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master

      - deploy:
          requires:
            - build

          filters:
            branches:
              only:
                - master
